"""
Smart Parking System v2.0 — Database Layer
SQLite database with 14 tables supporting multi-location parking,
user accounts, bookings, payments, AI recommendations, and chatbot history.

Tables:
  1.  parking_locations   — Registry of parking venues
  2.  parking_zones       — Subdivisions within a location
  3.  parking_config      — Per-zone sensor/capacity configuration
  4.  parking_status      — Live per-zone occupancy (updated every event)
  5.  occupancy_log       — Immutable event stream (every ENTRY/EXIT)
  6.  predictions         — ML predictions per zone
  7.  daily_summary       — Aggregated daily stats per zone
  8.  users               — User accounts
  9.  sessions            — Login sessions (token-based auth)
  10. bookings            — Parking reservations
  11. payments            — Payment records
  12. pricing_rules       — Per-location pricing tiers
  13. ai_recommendations  — Smart messages generated by AI per zone
  14. chatbot_history     — User ↔ AI conversation log
"""

import sqlite3
import os
import hashlib
import secrets
from datetime import datetime, timezone, timedelta


# ═══════════════════════════════════════════════════════════
# CONNECTION MANAGEMENT
# ═══════════════════════════════════════════════════════════

def get_connection(db_path: str) -> sqlite3.Connection:
    """Returns a connection with WAL mode, foreign keys ON,
    and row_factory set to sqlite3.Row for dict-like access."""
    os.makedirs(os.path.dirname(db_path), exist_ok=True)
    conn = sqlite3.connect(db_path)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    conn.row_factory = sqlite3.Row
    return conn


def _now_iso() -> str:
    """Returns current UTC time as ISO 8601 string."""
    return datetime.now(timezone.utc).isoformat(timespec='seconds')


def _today_iso() -> str:
    """Returns current UTC date as YYYY-MM-DD."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


# ═══════════════════════════════════════════════════════════
# SCHEMA — 14 TABLES
# ═══════════════════════════════════════════════════════════

_SCHEMA_SQL = """

-- ─── TABLE 1: Parking Locations ───
-- Each row is a physical venue (mall, airport, office, university, hospital).
CREATE TABLE IF NOT EXISTS parking_locations (
    location_id     TEXT PRIMARY KEY,
    name            TEXT NOT NULL,
    address         TEXT NOT NULL,
    city            TEXT NOT NULL,
    latitude        REAL NOT NULL,
    longitude       REAL NOT NULL,
    location_type   TEXT NOT NULL CHECK(location_type IN (
        'MALL', 'AIRPORT', 'CORPORATE', 'UNIVERSITY', 'HOSPITAL'
    )),
    operating_hours TEXT NOT NULL DEFAULT '00:00-23:59',
    image_url       TEXT,
    created_at      TEXT NOT NULL
);

-- ─── TABLE 2: Parking Zones ───
-- Subdivisions within a location (e.g., "Ground Floor", "Basement P1").
-- Each zone has its own capacity and sensor array.
CREATE TABLE IF NOT EXISTS parking_zones (
    zone_id         TEXT PRIMARY KEY,
    location_id     TEXT NOT NULL,
    zone_name       TEXT NOT NULL,
    max_capacity    INTEGER NOT NULL CHECK(max_capacity > 0),
    floor_level     TEXT,
    is_active       INTEGER NOT NULL DEFAULT 1,
    created_at      TEXT NOT NULL,
    FOREIGN KEY (location_id) REFERENCES parking_locations(location_id)
);

-- ─── TABLE 3: Parking Config ───
-- Per-zone technical configuration (sensor count, thresholds).
CREATE TABLE IF NOT EXISTS parking_config (
    zone_id         TEXT PRIMARY KEY,
    sensor_count    INTEGER NOT NULL DEFAULT 2,
    warning_threshold REAL NOT NULL DEFAULT 0.8,
    critical_threshold REAL NOT NULL DEFAULT 0.95,
    FOREIGN KEY (zone_id) REFERENCES parking_zones(zone_id)
);

-- ─── TABLE 4: Parking Status ───
-- Live occupancy per zone. Updated on every ENTRY/EXIT event.
CREATE TABLE IF NOT EXISTS parking_status (
    zone_id             TEXT PRIMARY KEY,
    current_count       INTEGER NOT NULL DEFAULT 0,
    max_capacity        INTEGER NOT NULL,
    available_slots     INTEGER NOT NULL,
    utilization_percent REAL NOT NULL DEFAULT 0.0,
    is_full             INTEGER NOT NULL DEFAULT 0,
    last_event_type     TEXT,
    last_updated        TEXT NOT NULL,
    FOREIGN KEY (zone_id) REFERENCES parking_zones(zone_id)
);

-- ─── TABLE 5: Occupancy Log ───
-- Immutable append-only event stream. Every ENTRY/EXIT ever recorded.
CREATE TABLE IF NOT EXISTS occupancy_log (
    event_id        INTEGER PRIMARY KEY AUTOINCREMENT,
    zone_id         TEXT NOT NULL,
    event_type      TEXT NOT NULL CHECK(event_type IN ('ENTRY', 'EXIT')),
    event_time      TEXT NOT NULL,
    occupancy_after INTEGER NOT NULL CHECK(occupancy_after >= 0),
    FOREIGN KEY (zone_id) REFERENCES parking_zones(zone_id)
);

-- ─── TABLE 6: Predictions ───
-- ML predictions per zone (predicted occupancy, peak hours, utilization).
CREATE TABLE IF NOT EXISTS predictions (
    prediction_id   INTEGER PRIMARY KEY AUTOINCREMENT,
    zone_id         TEXT NOT NULL,
    predicted_at    TEXT NOT NULL,
    predicted_count INTEGER NOT NULL,
    peak_hour_start TEXT,
    peak_hour_end   TEXT,
    utilization_avg REAL,
    model_type      TEXT DEFAULT 'linear_regression',
    mae             REAL,
    FOREIGN KEY (zone_id) REFERENCES parking_zones(zone_id)
);

-- ─── TABLE 7: Daily Summary ───
-- Aggregated daily statistics per zone.
CREATE TABLE IF NOT EXISTS daily_summary (
    date            TEXT NOT NULL,
    zone_id         TEXT NOT NULL,
    total_entries   INTEGER NOT NULL DEFAULT 0,
    total_exits     INTEGER NOT NULL DEFAULT 0,
    peak_count      INTEGER NOT NULL DEFAULT 0,
    avg_utilization REAL NOT NULL DEFAULT 0.0,
    PRIMARY KEY (date, zone_id),
    FOREIGN KEY (zone_id) REFERENCES parking_zones(zone_id)
);

-- ─── TABLE 8: Users ───
-- User accounts for the parking system.
CREATE TABLE IF NOT EXISTS users (
    user_id         INTEGER PRIMARY KEY AUTOINCREMENT,
    name            TEXT NOT NULL,
    email           TEXT NOT NULL UNIQUE,
    phone           TEXT,
    password_hash   TEXT NOT NULL,
    vehicle_plate   TEXT,
    created_at      TEXT NOT NULL,
    updated_at      TEXT NOT NULL
);

-- ─── TABLE 9: Sessions ───
-- Login sessions with token-based authentication.
CREATE TABLE IF NOT EXISTS sessions (
    session_id      INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id         INTEGER NOT NULL,
    token           TEXT NOT NULL UNIQUE,
    created_at      TEXT NOT NULL,
    expires_at      TEXT NOT NULL,
    is_active       INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- ─── TABLE 10: Bookings ───
-- Parking reservations by users.
CREATE TABLE IF NOT EXISTS bookings (
    booking_id      INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id         INTEGER NOT NULL,
    zone_id         TEXT NOT NULL,
    booking_time    TEXT NOT NULL,
    start_time      TEXT NOT NULL,
    end_time        TEXT,
    status          TEXT NOT NULL DEFAULT 'CONFIRMED' CHECK(status IN (
        'CONFIRMED', 'ACTIVE', 'COMPLETED', 'CANCELLED'
    )),
    vehicle_plate   TEXT,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (zone_id) REFERENCES parking_zones(zone_id)
);

-- ─── TABLE 11: Payments ───
-- Payment records linked to bookings.
CREATE TABLE IF NOT EXISTS payments (
    payment_id      INTEGER PRIMARY KEY AUTOINCREMENT,
    booking_id      INTEGER NOT NULL,
    user_id         INTEGER NOT NULL,
    amount          REAL NOT NULL CHECK(amount >= 0),
    currency        TEXT NOT NULL DEFAULT 'INR',
    method          TEXT NOT NULL DEFAULT 'SIMULATED' CHECK(method IN (
        'SIMULATED', 'UPI', 'CARD', 'WALLET'
    )),
    status          TEXT NOT NULL DEFAULT 'PENDING' CHECK(status IN (
        'PENDING', 'PAID', 'REFUNDED', 'FAILED'
    )),
    transaction_id  TEXT,
    created_at      TEXT NOT NULL,
    FOREIGN KEY (booking_id) REFERENCES bookings(booking_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- ─── TABLE 12: Pricing Rules ───
-- Per-location pricing tiers.
CREATE TABLE IF NOT EXISTS pricing_rules (
    pricing_id      INTEGER PRIMARY KEY AUTOINCREMENT,
    location_id     TEXT NOT NULL,
    rate_per_hour   REAL NOT NULL CHECK(rate_per_hour >= 0),
    rate_per_day    REAL NOT NULL CHECK(rate_per_day >= 0),
    currency        TEXT NOT NULL DEFAULT 'INR',
    surge_multiplier REAL NOT NULL DEFAULT 1.0,
    is_active       INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (location_id) REFERENCES parking_locations(location_id)
);

-- ─── TABLE 13: AI Recommendations ───
-- Smart messages generated by the AI engine per zone.
CREATE TABLE IF NOT EXISTS ai_recommendations (
    rec_id          INTEGER PRIMARY KEY AUTOINCREMENT,
    zone_id         TEXT NOT NULL,
    message         TEXT NOT NULL,
    category        TEXT NOT NULL CHECK(category IN (
        'CALM', 'INFORMATIONAL', 'ALERT', 'URGENT', 'CRITICAL', 'FULL_REDIRECT'
    )),
    utilization_at  REAL NOT NULL,
    alternative_zone TEXT,
    created_at      TEXT NOT NULL,
    FOREIGN KEY (zone_id) REFERENCES parking_zones(zone_id)
);

-- ─── TABLE 14: Chatbot History ───
-- User ↔ AI conversation log.
CREATE TABLE IF NOT EXISTS chatbot_history (
    chat_id         INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id         INTEGER,
    user_query      TEXT NOT NULL,
    bot_response    TEXT NOT NULL,
    intent          TEXT,
    created_at      TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- ─── INDEXES for query performance ───
CREATE INDEX IF NOT EXISTS idx_occupancy_zone_time
    ON occupancy_log(zone_id, event_time);
CREATE INDEX IF NOT EXISTS idx_daily_zone_date
    ON daily_summary(zone_id, date);
CREATE INDEX IF NOT EXISTS idx_bookings_user
    ON bookings(user_id, status);
CREATE INDEX IF NOT EXISTS idx_payments_user
    ON payments(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_token
    ON sessions(token, is_active);
CREATE INDEX IF NOT EXISTS idx_zones_location
    ON parking_zones(location_id);
"""


# ═══════════════════════════════════════════════════════════
# INITIALIZATION
# ═══════════════════════════════════════════════════════════

def init_db(db_path: str, locations: list | None = None) -> None:
    """Creates all 14 tables and seeds location/zone/pricing data
    from the LOCATIONS config if not already present."""
    conn = get_connection(db_path)
    try:
        conn.executescript(_SCHEMA_SQL)

        if locations:
            now = _now_iso()
            for loc in locations:
                # Check if location already exists
                existing = conn.execute(
                    "SELECT 1 FROM parking_locations WHERE location_id = ?",
                    (loc["location_id"],)
                ).fetchone()
                if existing:
                    continue

                # Insert location
                conn.execute(
                    "INSERT INTO parking_locations "
                    "(location_id, name, address, city, latitude, longitude, "
                    "location_type, operating_hours, image_url, created_at) "
                    "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                    (loc["location_id"], loc["name"], loc["address"],
                     loc["city"], loc["latitude"], loc["longitude"],
                     loc["location_type"], loc["operating_hours"],
                     loc.get("image_url"), now)
                )

                # Insert zones and their status rows
                for zone in loc["zones"]:
                    conn.execute(
                        "INSERT INTO parking_zones "
                        "(zone_id, location_id, zone_name, max_capacity, created_at) "
                        "VALUES (?, ?, ?, ?, ?)",
                        (zone["zone_id"], loc["location_id"],
                         zone["zone_name"], zone["max_capacity"], now)
                    )
                    # Initialize parking_config with defaults
                    conn.execute(
                        "INSERT INTO parking_config "
                        "(zone_id, sensor_count, warning_threshold, critical_threshold) "
                        "VALUES (?, 2, 0.8, 0.95)",
                        (zone["zone_id"],)
                    )
                    # Initialize parking_status at 0 occupancy
                    conn.execute(
                        "INSERT INTO parking_status "
                        "(zone_id, current_count, max_capacity, available_slots, "
                        "utilization_percent, is_full, last_updated) "
                        "VALUES (?, 0, ?, ?, 0.0, 0, ?)",
                        (zone["zone_id"], zone["max_capacity"],
                         zone["max_capacity"], now)
                    )

                # Insert pricing rules
                pricing = loc.get("pricing", {})
                conn.execute(
                    "INSERT INTO pricing_rules "
                    "(location_id, rate_per_hour, rate_per_day, currency) "
                    "VALUES (?, ?, ?, ?)",
                    (loc["location_id"],
                     pricing.get("rate_per_hour", 0),
                     pricing.get("rate_per_day", 0),
                     pricing.get("currency", "INR"))
                )

            conn.commit()
    finally:
        conn.close()


# ═══════════════════════════════════════════════════════════
# LOCATION & ZONE QUERIES
# ═══════════════════════════════════════════════════════════

def get_all_locations(db_path: str) -> list[dict]:
    """Returns all parking locations with aggregated zone data and zone list."""
    conn = get_connection(db_path)
    try:
        # 1. Fetch base location aggregates
        rows = conn.execute("""
            SELECT
                pl.*,
                COALESCE(SUM(pz.max_capacity), 0) AS total_capacity,
                COUNT(pz.zone_id) AS zone_count,
                COALESCE(SUM(ps.current_count), 0) AS total_occupied,
                COALESCE(SUM(ps.available_slots), 0) AS total_available
            FROM parking_locations pl
            LEFT JOIN parking_zones pz ON pl.location_id = pz.location_id
            LEFT JOIN parking_status ps ON pz.zone_id = ps.zone_id
            GROUP BY pl.location_id
            ORDER BY pl.name
        """).fetchall()

        # 2. Fetch all active pricing rules into a lookup map
        pricing_rows = conn.execute("""
            SELECT location_id, rate_per_hour, rate_per_day, currency
            FROM pricing_rules WHERE is_active = 1
        """).fetchall()
        pricing_map = {r["location_id"]: dict(r) for r in pricing_rows}

        # 3. Fetch all zones and map by location_id
        zone_rows = conn.execute("""
            SELECT pz.location_id, pz.zone_id, pz.zone_name, pz.max_capacity,
                   COALESCE(ps.current_count, 0) AS current_count,
                   COALESCE(ps.available_slots, pz.max_capacity) AS available_slots
            FROM parking_zones pz
            LEFT JOIN parking_status ps ON pz.zone_id = ps.zone_id
            ORDER BY pz.zone_name
        """).fetchall()
        
        zone_map = {}
        for z in zone_rows:
            loc_id = z["location_id"]
            if loc_id not in zone_map:
                zone_map[loc_id] = []
            zd = dict(z)
            del zd["location_id"]
            zone_map[loc_id].append(zd)

        result = []
        for row in rows:
            d = dict(row)
            loc_id = d["location_id"]
            
            total_cap = d["total_capacity"]
            total_occ = d["total_occupied"]
            d["utilization_percent"] = round(
                (total_occ / total_cap * 100) if total_cap > 0 else 0.0, 1
            )
            d["is_full"] = total_occ >= total_cap
            
            if loc_id in pricing_map:
                p = pricing_map[loc_id]
                d["rate_per_hour"] = p["rate_per_hour"]
                d["rate_per_day"] = p["rate_per_day"]
                d["currency"] = p["currency"]
                
            d["zones"] = zone_map.get(loc_id, [])
            result.append(d)
            
        return result
    finally:
        conn.close()


def get_location(db_path: str, location_id: str) -> dict | None:
    """Returns a single location with zone details."""
    conn = get_connection(db_path)
    try:
        loc = conn.execute(
            "SELECT * FROM parking_locations WHERE location_id = ?",
            (location_id,)
        ).fetchone()
        if not loc:
            return None

        d = dict(loc)

        # Get zones with status
        zones = conn.execute("""
            SELECT pz.*, ps.current_count, ps.available_slots,
                   ps.utilization_percent, ps.is_full, ps.last_updated
            FROM parking_zones pz
            LEFT JOIN parking_status ps ON pz.zone_id = ps.zone_id
            WHERE pz.location_id = ?
            ORDER BY pz.zone_name
        """, (location_id,)).fetchall()
        d["zones"] = [dict(z) for z in zones]

        # Aggregate totals
        d["zone_count"] = len(d["zones"])
        d["total_capacity"] = sum(z["max_capacity"] for z in d["zones"])
        d["total_occupied"] = sum(
            z.get("current_count", 0) or 0 for z in d["zones"]
        )
        d["total_available"] = d["total_capacity"] - d["total_occupied"]
        d["utilization_percent"] = round(
            (d["total_occupied"] / d["total_capacity"] * 100)
            if d["total_capacity"] > 0 else 0.0, 1
        )
        d["is_full"] = d["total_occupied"] >= d["total_capacity"]

        # Get pricing
        pricing = conn.execute(
            "SELECT rate_per_hour, rate_per_day, currency "
            "FROM pricing_rules WHERE location_id = ? AND is_active = 1",
            (location_id,)
        ).fetchone()
        if pricing:
            d["rate_per_hour"] = pricing["rate_per_hour"]
            d["rate_per_day"] = pricing["rate_per_day"]
            d["currency"] = pricing["currency"]

        return d
    finally:
        conn.close()


def get_zones_for_location(db_path: str, location_id: str) -> list[dict]:
    """Returns all zones for a location with live status."""
    conn = get_connection(db_path)
    try:
        rows = conn.execute("""
            SELECT pz.*, ps.current_count, ps.available_slots,
                   ps.utilization_percent, ps.is_full, ps.last_event_type,
                   ps.last_updated
            FROM parking_zones pz
            LEFT JOIN parking_status ps ON pz.zone_id = ps.zone_id
            WHERE pz.location_id = ?
            ORDER BY pz.zone_name
        """, (location_id,)).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


# ═══════════════════════════════════════════════════════════
# PARKING STATUS
# ═══════════════════════════════════════════════════════════

def update_status(db_path: str, zone_id: str,
                  current_count: int, max_capacity: int,
                  event_type: str = None) -> dict:
    """Upserts parking_status for a zone with derived fields.
    Returns the complete status dict."""
    available = max(0, max_capacity - current_count)
    utilization = (current_count / max_capacity * 100) if max_capacity > 0 else 0.0
    is_full = 1 if current_count >= max_capacity else 0
    now = _now_iso()

    conn = get_connection(db_path)
    try:
        conn.execute(
            "INSERT INTO parking_status "
            "(zone_id, current_count, max_capacity, available_slots, "
            "utilization_percent, is_full, last_event_type, last_updated) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?) "
            "ON CONFLICT(zone_id) DO UPDATE SET "
            "current_count = excluded.current_count, "
            "max_capacity = excluded.max_capacity, "
            "available_slots = excluded.available_slots, "
            "utilization_percent = excluded.utilization_percent, "
            "is_full = excluded.is_full, "
            "last_event_type = excluded.last_event_type, "
            "last_updated = excluded.last_updated",
            (zone_id, current_count, max_capacity, available,
             round(utilization, 1), is_full, event_type, now)
        )
        conn.commit()
    finally:
        conn.close()

    return {
        "zone_id": zone_id,
        "current_count": current_count,
        "max_capacity": max_capacity,
        "available_slots": available,
        "utilization_percent": round(utilization, 1),
        "is_full": bool(is_full),
        "last_event_type": event_type,
        "last_updated": now
    }


def get_status(db_path: str, zone_id: str) -> dict | None:
    """Returns current parking_status for a specific zone."""
    conn = get_connection(db_path)
    try:
        row = conn.execute(
            "SELECT ps.*, pz.zone_name, pz.location_id "
            "FROM parking_status ps "
            "JOIN parking_zones pz ON ps.zone_id = pz.zone_id "
            "WHERE ps.zone_id = ?",
            (zone_id,)
        ).fetchone()
        if not row:
            return None
        d = dict(row)
        d["is_full"] = bool(d["is_full"])
        return d
    finally:
        conn.close()


def get_all_statuses(db_path: str) -> list[dict]:
    """Returns parking_status for all zones, joined with zone and location info."""
    conn = get_connection(db_path)
    try:
        rows = conn.execute("""
            SELECT ps.*, pz.zone_name, pz.location_id, pl.name AS location_name
            FROM parking_status ps
            JOIN parking_zones pz ON ps.zone_id = pz.zone_id
            JOIN parking_locations pl ON pz.location_id = pl.location_id
            ORDER BY pl.name, pz.zone_name
        """).fetchall()
        result = []
        for r in rows:
            d = dict(r)
            d["is_full"] = bool(d["is_full"])
            result.append(d)
        return result
    finally:
        conn.close()


# ═══════════════════════════════════════════════════════════
# EVENT LOGGING
# ═══════════════════════════════════════════════════════════

def log_event(db_path: str, zone_id: str,
              event_type: str, occupancy_after: int,
              event_time: str | None = None) -> int:
    """Appends to occupancy_log. Returns event_id."""
    if event_type not in ("ENTRY", "EXIT"):
        raise ValueError(f"Invalid event_type: {event_type}")
    if event_time is None:
        event_time = _now_iso()

    conn = get_connection(db_path)
    try:
        cursor = conn.execute(
            "INSERT INTO occupancy_log "
            "(zone_id, event_type, event_time, occupancy_after) "
            "VALUES (?, ?, ?, ?)",
            (zone_id, event_type, event_time, occupancy_after)
        )
        conn.commit()
        return cursor.lastrowid
    finally:
        conn.close()


def batch_log_events(db_path: str, events: list[tuple]) -> int:
    """Bulk inserts events into occupancy_log in a single transaction.
    Each event is a tuple: (zone_id, event_type, event_time, occupancy_after).
    Returns total events inserted."""
    if not events:
        return 0
    conn = get_connection(db_path)
    try:
        conn.executemany(
            "INSERT INTO occupancy_log "
            "(zone_id, event_type, event_time, occupancy_after) "
            "VALUES (?, ?, ?, ?)",
            events
        )
        conn.commit()
        return len(events)
    finally:
        conn.close()


def get_history(db_path: str, zone_id: str,
                hours: int = 24) -> list[dict]:
    """Returns occupancy_log events from last N hours for a zone."""
    cutoff = (datetime.now(timezone.utc) - timedelta(hours=hours)).isoformat(
        timespec='seconds')

    conn = get_connection(db_path)
    try:
        rows = conn.execute(
            "SELECT event_id, event_type, event_time, occupancy_after "
            "FROM occupancy_log "
            "WHERE zone_id = ? AND event_time >= ? "
            "ORDER BY event_time DESC",
            (zone_id, cutoff)
        ).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


def get_all_events(db_path: str, zone_id: str) -> list[dict]:
    """Returns ALL occupancy_log events for a zone, ordered by time."""
    conn = get_connection(db_path)
    try:
        rows = conn.execute(
            "SELECT event_id, event_type, event_time, occupancy_after "
            "FROM occupancy_log "
            "WHERE zone_id = ? "
            "ORDER BY event_time ASC",
            (zone_id,)
        ).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


def get_location_events(db_path: str, location_id: str) -> list[dict]:
    """Returns ALL events for ALL zones in a location, ordered by time."""
    conn = get_connection(db_path)
    try:
        rows = conn.execute("""
            SELECT ol.event_id, ol.zone_id, ol.event_type,
                   ol.event_time, ol.occupancy_after, pz.zone_name
            FROM occupancy_log ol
            JOIN parking_zones pz ON ol.zone_id = pz.zone_id
            WHERE pz.location_id = ?
            ORDER BY ol.event_time ASC
        """, (location_id,)).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


# ═══════════════════════════════════════════════════════════
# PREDICTIONS
# ═══════════════════════════════════════════════════════════

def save_prediction(db_path: str, zone_id: str,
                    predicted_count: int, peak_hour_start: str,
                    peak_hour_end: str, utilization_avg: float,
                    model_type: str = "linear_regression",
                    mae: float = None) -> int:
    """Inserts into predictions table. Returns prediction_id."""
    conn = get_connection(db_path)
    try:
        cursor = conn.execute(
            "INSERT INTO predictions "
            "(zone_id, predicted_at, predicted_count, "
            "peak_hour_start, peak_hour_end, utilization_avg, "
            "model_type, mae) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
            (zone_id, _now_iso(), predicted_count,
             peak_hour_start, peak_hour_end,
             round(utilization_avg, 1), model_type, mae)
        )
        conn.commit()
        return cursor.lastrowid
    finally:
        conn.close()


def get_latest_prediction(db_path: str, zone_id: str) -> dict | None:
    """Returns most recent prediction for a zone."""
    conn = get_connection(db_path)
    try:
        row = conn.execute(
            "SELECT * FROM predictions "
            "WHERE zone_id = ? "
            "ORDER BY predicted_at DESC LIMIT 1",
            (zone_id,)
        ).fetchone()
        return dict(row) if row else None
    finally:
        conn.close()


def get_location_predictions(db_path: str, location_id: str) -> list[dict]:
    """Returns latest prediction for each zone in a location."""
    conn = get_connection(db_path)
    try:
        rows = conn.execute("""
            SELECT p.*, pz.zone_name
            FROM predictions p
            JOIN parking_zones pz ON p.zone_id = pz.zone_id
            WHERE pz.location_id = ?
            AND p.predicted_at = (
                SELECT MAX(p2.predicted_at)
                FROM predictions p2
                WHERE p2.zone_id = p.zone_id
            )
            ORDER BY pz.zone_name
        """, (location_id,)).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


# ═══════════════════════════════════════════════════════════
# ANALYTICS
# ═══════════════════════════════════════════════════════════

def aggregate_daily(db_path: str, zone_id: str, date: str,
                    max_capacity: int) -> dict:
    """Computes and stores daily_summary for a zone on a given date."""
    conn = get_connection(db_path)
    try:
        entries = conn.execute(
            "SELECT COUNT(*) as cnt FROM occupancy_log "
            "WHERE zone_id = ? AND event_type = 'ENTRY' "
            "AND event_time LIKE ?",
            (zone_id, f"{date}%")
        ).fetchone()["cnt"]

        exits = conn.execute(
            "SELECT COUNT(*) as cnt FROM occupancy_log "
            "WHERE zone_id = ? AND event_type = 'EXIT' "
            "AND event_time LIKE ?",
            (zone_id, f"{date}%")
        ).fetchone()["cnt"]

        peak_row = conn.execute(
            "SELECT MAX(occupancy_after) as peak FROM occupancy_log "
            "WHERE zone_id = ? AND event_time LIKE ?",
            (zone_id, f"{date}%")
        ).fetchone()
        peak_count = peak_row["peak"] if peak_row["peak"] is not None else 0

        avg_row = conn.execute(
            "SELECT AVG(occupancy_after) as avg_occ FROM occupancy_log "
            "WHERE zone_id = ? AND event_time LIKE ?",
            (zone_id, f"{date}%")
        ).fetchone()
        avg_occ = avg_row["avg_occ"] if avg_row["avg_occ"] is not None else 0
        avg_util = (avg_occ / max_capacity * 100) if max_capacity > 0 else 0.0

        conn.execute(
            "INSERT INTO daily_summary "
            "(date, zone_id, total_entries, total_exits, "
            "peak_count, avg_utilization) "
            "VALUES (?, ?, ?, ?, ?, ?) "
            "ON CONFLICT(date, zone_id) DO UPDATE SET "
            "total_entries = excluded.total_entries, "
            "total_exits = excluded.total_exits, "
            "peak_count = excluded.peak_count, "
            "avg_utilization = excluded.avg_utilization",
            (date, zone_id, entries, exits, peak_count, round(avg_util, 1))
        )
        conn.commit()

        return {
            "date": date, "zone_id": zone_id,
            "total_entries": entries, "total_exits": exits,
            "peak_count": peak_count, "avg_utilization": round(avg_util, 1)
        }
    finally:
        conn.close()


def get_daily_summaries(db_path: str, zone_id: str,
                        days: int = 7) -> list[dict]:
    """Returns daily_summary rows for last N days for a zone."""
    conn = get_connection(db_path)
    try:
        rows = conn.execute(
            "SELECT * FROM daily_summary "
            "WHERE zone_id = ? "
            "ORDER BY date DESC LIMIT ?",
            (zone_id, days)
        ).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


def get_hourly_averages(db_path: str, zone_id: str) -> list[dict]:
    """Returns average occupancy per hour (0-23) for a zone."""
    conn = get_connection(db_path)
    try:
        rows = conn.execute(
            "SELECT CAST(SUBSTR(event_time, 12, 2) AS INTEGER) as hour, "
            "AVG(occupancy_after) as avg_occupancy, "
            "COUNT(*) as event_count "
            "FROM occupancy_log "
            "WHERE zone_id = ? "
            "GROUP BY hour "
            "ORDER BY hour",
            (zone_id,)
        ).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


# ═══════════════════════════════════════════════════════════
# USER MANAGEMENT
# ═══════════════════════════════════════════════════════════

def _hash_password(password: str) -> str:
    """Creates a SHA-256 hash of the password with a salt prefix."""
    salt = "sp_v2_salt_"
    return hashlib.sha256((salt + password).encode('utf-8')).hexdigest()


def create_user(db_path: str, name: str, email: str,
                password: str, phone: str = None,
                vehicle_plate: str = None) -> dict:
    """Creates a new user account. Returns user dict.
    Raises ValueError if email already exists."""
    now = _now_iso()
    pw_hash = _hash_password(password)

    conn = get_connection(db_path)
    try:
        existing = conn.execute(
            "SELECT 1 FROM users WHERE email = ?", (email,)
        ).fetchone()
        if existing:
            raise ValueError(f"Email already registered: {email}")

        cursor = conn.execute(
            "INSERT INTO users "
            "(name, email, phone, password_hash, vehicle_plate, "
            "created_at, updated_at) "
            "VALUES (?, ?, ?, ?, ?, ?, ?)",
            (name, email, phone, pw_hash, vehicle_plate, now, now)
        )
        conn.commit()
        return {
            "user_id": cursor.lastrowid,
            "name": name, "email": email,
            "phone": phone, "vehicle_plate": vehicle_plate,
            "created_at": now
        }
    finally:
        conn.close()


def authenticate_user(db_path: str, email: str, password: str) -> dict | None:
    """Validates credentials. Returns user dict if valid, None if not."""
    pw_hash = _hash_password(password)
    conn = get_connection(db_path)
    try:
        row = conn.execute(
            "SELECT user_id, name, email, phone, vehicle_plate, created_at "
            "FROM users WHERE email = ? AND password_hash = ?",
            (email, pw_hash)
        ).fetchone()
        return dict(row) if row else None
    finally:
        conn.close()


def get_user_by_id(db_path: str, user_id: int) -> dict | None:
    """Returns user data by user_id (excludes password_hash)."""
    conn = get_connection(db_path)
    try:
        row = conn.execute(
            "SELECT user_id, name, email, phone, vehicle_plate, created_at "
            "FROM users WHERE user_id = ?",
            (user_id,)
        ).fetchone()
        return dict(row) if row else None
    finally:
        conn.close()


# ═══════════════════════════════════════════════════════════
# SESSION MANAGEMENT
# ═══════════════════════════════════════════════════════════

def create_session(db_path: str, user_id: int,
                   expiry_hours: int = 24) -> str:
    """Creates a login session. Returns the token string."""
    token = secrets.token_hex(32)
    now = _now_iso()
    expires = (datetime.now(timezone.utc) + timedelta(hours=expiry_hours)
               ).isoformat(timespec='seconds')

    conn = get_connection(db_path)
    try:
        conn.execute(
            "INSERT INTO sessions (user_id, token, created_at, expires_at) "
            "VALUES (?, ?, ?, ?)",
            (user_id, token, now, expires)
        )
        conn.commit()
        return token
    finally:
        conn.close()


def validate_session(db_path: str, token: str) -> dict | None:
    """Validates a session token. Returns user data if valid."""
    now = _now_iso()
    conn = get_connection(db_path)
    try:
        row = conn.execute("""
            SELECT s.user_id, u.name, u.email, u.phone, u.vehicle_plate
            FROM sessions s
            JOIN users u ON s.user_id = u.user_id
            WHERE s.token = ? AND s.is_active = 1 AND s.expires_at > ?
        """, (token, now)).fetchone()
        return dict(row) if row else None
    finally:
        conn.close()


def invalidate_session(db_path: str, token: str) -> bool:
    """Deactivates a session token. Returns True if found."""
    conn = get_connection(db_path)
    try:
        cursor = conn.execute(
            "UPDATE sessions SET is_active = 0 WHERE token = ?",
            (token,)
        )
        conn.commit()
        return cursor.rowcount > 0
    finally:
        conn.close()


# ═══════════════════════════════════════════════════════════
# BOOKINGS
# ═══════════════════════════════════════════════════════════

def create_booking(db_path: str, user_id: int, zone_id: str,
                   start_time: str, vehicle_plate: str = None) -> dict:
    """Creates a parking booking. Returns booking dict.
    Raises ValueError if zone is full."""
    now = _now_iso()

    conn = get_connection(db_path)
    try:
        # Check zone availability
        status = conn.execute(
            "SELECT current_count, max_capacity FROM parking_status "
            "WHERE zone_id = ?", (zone_id,)
        ).fetchone()

        if status and status["current_count"] >= status["max_capacity"]:
            raise ValueError(f"Zone {zone_id} is full. No spots available.")

        cursor = conn.execute(
            "INSERT INTO bookings "
            "(user_id, zone_id, booking_time, start_time, "
            "status, vehicle_plate) "
            "VALUES (?, ?, ?, ?, 'CONFIRMED', ?)",
            (user_id, zone_id, now, start_time, vehicle_plate)
        )
        conn.commit()

        return {
            "booking_id": cursor.lastrowid,
            "user_id": user_id,
            "zone_id": zone_id,
            "booking_time": now,
            "start_time": start_time,
            "status": "CONFIRMED",
            "vehicle_plate": vehicle_plate
        }
    finally:
        conn.close()


def get_user_bookings(db_path: str, user_id: int) -> list[dict]:
    """Returns all bookings for a user with zone and location names."""
    conn = get_connection(db_path)
    try:
        rows = conn.execute("""
            SELECT b.*, pz.zone_name, pl.name AS location_name,
                   pl.location_id
            FROM bookings b
            JOIN parking_zones pz ON b.zone_id = pz.zone_id
            JOIN parking_locations pl ON pz.location_id = pl.location_id
            WHERE b.user_id = ?
            ORDER BY b.booking_time DESC
        """, (user_id,)).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


def cancel_booking(db_path: str, booking_id: int, user_id: int) -> bool:
    """Cancels a booking. Returns True if successful."""
    conn = get_connection(db_path)
    try:
        cursor = conn.execute(
            "UPDATE bookings SET status = 'CANCELLED' "
            "WHERE booking_id = ? AND user_id = ? AND status = 'CONFIRMED'",
            (booking_id, user_id)
        )
        conn.commit()
        return cursor.rowcount > 0
    finally:
        conn.close()


def complete_booking(db_path: str, booking_id: int) -> bool:
    """Marks a booking as completed with end_time. Returns True if successful."""
    now = _now_iso()
    conn = get_connection(db_path)
    try:
        cursor = conn.execute(
            "UPDATE bookings SET status = 'COMPLETED', end_time = ? "
            "WHERE booking_id = ? AND status IN ('CONFIRMED', 'ACTIVE')",
            (now, booking_id)
        )
        conn.commit()
        return cursor.rowcount > 0
    finally:
        conn.close()


# ═══════════════════════════════════════════════════════════
# PAYMENTS
# ═══════════════════════════════════════════════════════════

def create_payment(db_path: str, booking_id: int, user_id: int,
                   amount: float, method: str = "SIMULATED") -> dict:
    """Creates a payment record. Returns payment dict."""
    now = _now_iso()
    txn_id = f"TXN_{secrets.token_hex(8).upper()}"

    conn = get_connection(db_path)
    try:
        cursor = conn.execute(
            "INSERT INTO payments "
            "(booking_id, user_id, amount, method, status, "
            "transaction_id, created_at) "
            "VALUES (?, ?, ?, ?, 'PENDING', ?, ?)",
            (booking_id, user_id, amount, method, txn_id, now)
        )
        conn.commit()
        return {
            "payment_id": cursor.lastrowid,
            "booking_id": booking_id,
            "user_id": user_id,
            "amount": amount,
            "method": method,
            "status": "PENDING",
            "transaction_id": txn_id,
            "created_at": now
        }
    finally:
        conn.close()


def process_payment(db_path: str, payment_id: int) -> bool:
    """Simulates payment processing. Changes status from PENDING to PAID."""
    conn = get_connection(db_path)
    try:
        cursor = conn.execute(
            "UPDATE payments SET status = 'PAID' "
            "WHERE payment_id = ? AND status = 'PENDING'",
            (payment_id,)
        )
        conn.commit()
        return cursor.rowcount > 0
    finally:
        conn.close()


def get_user_payments(db_path: str, user_id: int) -> list[dict]:
    """Returns all payment records for a user."""
    conn = get_connection(db_path)
    try:
        rows = conn.execute("""
            SELECT p.*, b.zone_id, pz.zone_name, pl.name AS location_name
            FROM payments p
            JOIN bookings b ON p.booking_id = b.booking_id
            JOIN parking_zones pz ON b.zone_id = pz.zone_id
            JOIN parking_locations pl ON pz.location_id = pl.location_id
            WHERE p.user_id = ?
            ORDER BY p.created_at DESC
        """, (user_id,)).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


def calculate_parking_fee(db_path: str, location_id: str,
                          hours: float) -> dict:
    """Calculates the parking fee for given duration at a location."""
    conn = get_connection(db_path)
    try:
        pricing = conn.execute(
            "SELECT rate_per_hour, rate_per_day, currency, surge_multiplier "
            "FROM pricing_rules WHERE location_id = ? AND is_active = 1",
            (location_id,)
        ).fetchone()
        if not pricing:
            return {"amount": 0, "currency": "INR", "breakdown": "No pricing set"}

        rate_hr = pricing["rate_per_hour"]
        rate_day = pricing["rate_per_day"]
        surge = pricing["surge_multiplier"]

        # Use daily rate if cheaper for stays > X hours
        hourly_cost = hours * rate_hr * surge
        daily_cost = rate_day * surge
        if hours >= 8 and daily_cost < hourly_cost:
            amount = daily_cost
            breakdown = f"Daily rate: {rate_day} x {surge} surge = {amount}"
        else:
            amount = hourly_cost
            breakdown = f"{hours}h x {rate_hr}/hr x {surge} surge = {amount}"

        return {
            "amount": round(amount, 2),
            "currency": pricing["currency"],
            "breakdown": breakdown,
            "surge_multiplier": surge
        }
    finally:
        conn.close()


# ═══════════════════════════════════════════════════════════
# AI RECOMMENDATIONS
# ═══════════════════════════════════════════════════════════

def save_recommendation(db_path: str, zone_id: str, message: str,
                        category: str, utilization_at: float,
                        alternative_zone: str = None) -> int:
    """Saves an AI recommendation. Returns rec_id."""
    conn = get_connection(db_path)
    try:
        cursor = conn.execute(
            "INSERT INTO ai_recommendations "
            "(zone_id, message, category, utilization_at, "
            "alternative_zone, created_at) "
            "VALUES (?, ?, ?, ?, ?, ?)",
            (zone_id, message, category, utilization_at,
             alternative_zone, _now_iso())
        )
        conn.commit()
        return cursor.lastrowid
    finally:
        conn.close()


def get_latest_recommendation(db_path: str, zone_id: str) -> dict | None:
    """Returns the most recent AI recommendation for a zone."""
    conn = get_connection(db_path)
    try:
        row = conn.execute(
            "SELECT * FROM ai_recommendations "
            "WHERE zone_id = ? ORDER BY created_at DESC LIMIT 1",
            (zone_id,)
        ).fetchone()
        return dict(row) if row else None
    finally:
        conn.close()


# ═══════════════════════════════════════════════════════════
# CHATBOT HISTORY
# ═══════════════════════════════════════════════════════════

def save_chat_message(db_path: str, user_query: str,
                      bot_response: str, intent: str = None,
                      user_id: int = None) -> int:
    """Saves a chatbot conversation exchange. Returns chat_id."""
    conn = get_connection(db_path)
    try:
        cursor = conn.execute(
            "INSERT INTO chatbot_history "
            "(user_id, user_query, bot_response, intent, created_at) "
            "VALUES (?, ?, ?, ?, ?)",
            (user_id, user_query, bot_response, intent, _now_iso())
        )
        conn.commit()
        return cursor.lastrowid
    finally:
        conn.close()


def get_chat_history(db_path: str, user_id: int = None,
                     limit: int = 50) -> list[dict]:
    """Returns recent chatbot messages, optionally filtered by user."""
    conn = get_connection(db_path)
    try:
        if user_id:
            rows = conn.execute(
                "SELECT * FROM chatbot_history "
                "WHERE user_id = ? ORDER BY created_at DESC LIMIT ?",
                (user_id, limit)
            ).fetchall()
        else:
            rows = conn.execute(
                "SELECT * FROM chatbot_history "
                "ORDER BY created_at DESC LIMIT ?",
                (limit,)
            ).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


# ═══════════════════════════════════════════════════════════
# STANDALONE VERIFICATION
# ═══════════════════════════════════════════════════════════

if __name__ == "__main__":
    import sys
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    from backend.config import DB_PATH, LOCATIONS

    print("=" * 60)
    print("  SMART PARKING SYSTEM v2.0 — Database Verification")
    print("=" * 60)

    # Delete existing DB for fresh test
    if os.path.exists(DB_PATH):
        os.remove(DB_PATH)
        print(f"\n[CLEAN] Removed old database")

    print(f"\n[INIT] Creating 14-table schema with {len(LOCATIONS)} locations...")
    init_db(DB_PATH, LOCATIONS)

    # Verify tables
    conn = get_connection(DB_PATH)
    tables = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"
    ).fetchall()
    table_names = [t["name"] for t in tables]
    print(f"[OK] Tables created: {len(table_names)}")
    for t in table_names:
        print(f"     - {t}")

    # Verify locations
    locs = get_all_locations(DB_PATH)
    print(f"\n[OK] Locations: {len(locs)}")
    for loc in locs:
        print(f"     - {loc['name']} ({loc['location_type']}) "
              f"| {loc['zone_count']} zones | {loc['total_capacity']} slots")

    # Test status update
    print("\n[TEST] Updating status for LOC_MALL_GF (count=50)...")
    status = update_status(DB_PATH, "LOC_MALL_GF", 50, 100, "ENTRY")
    print(f"     - Count: {status['current_count']}/{status['max_capacity']}")
    print(f"     - Available: {status['available_slots']}")
    print(f"     - Utilization: {status['utilization_percent']}%")
    print(f"     - Is Full: {status['is_full']}")

    # Test event logging
    print("\n[TEST] Logging ENTRY event...")
    eid = log_event(DB_PATH, "LOC_MALL_GF", "ENTRY", 51)
    print(f"     - Event ID: {eid}")

    # Test user creation
    print("\n[TEST] Creating test user...")
    user = create_user(DB_PATH, "Test User", "test@example.com",
                       "password123", "+91-9876543210", "CH-01-AB-1234")
    print(f"     - User ID: {user['user_id']}")
    print(f"     - Name: {user['name']}")

    # Test authentication
    print("\n[TEST] Authenticating user...")
    auth = authenticate_user(DB_PATH, "test@example.com", "password123")
    print(f"     - Auth result: {'SUCCESS' if auth else 'FAILED'}")

    # Test session
    print("\n[TEST] Creating session...")
    token = create_session(DB_PATH, user["user_id"])
    print(f"     - Token: {token[:16]}...")
    valid = validate_session(DB_PATH, token)
    print(f"     - Session valid: {'YES' if valid else 'NO'}")

    # Test booking
    print("\n[TEST] Creating booking...")
    booking = create_booking(DB_PATH, user["user_id"], "LOC_MALL_GF",
                             "2026-03-26T10:00:00", "CH-01-AB-1234")
    print(f"     - Booking ID: {booking['booking_id']}")
    print(f"     - Status: {booking['status']}")

    # Test payment
    print("\n[TEST] Creating payment...")
    payment = create_payment(DB_PATH, booking["booking_id"],
                             user["user_id"], 120.0)
    print(f"     - Payment ID: {payment['payment_id']}")
    print(f"     - Amount: {payment['amount']} INR")
    print(f"     - TXN: {payment['transaction_id']}")

    # Process payment
    print("\n[TEST] Processing payment...")
    paid = process_payment(DB_PATH, payment["payment_id"])
    print(f"     - Processed: {'YES' if paid else 'NO'}")

    # Test recommendation
    print("\n[TEST] Saving AI recommendation...")
    rec_id = save_recommendation(
        DB_PATH, "LOC_MALL_GF",
        "Getting busy! Only 50 spots left at Elante Mall Ground Floor.",
        "ALERT", 50.0, "LOC_MALL_B1"
    )
    print(f"     - Recommendation ID: {rec_id}")

    # Test chatbot
    print("\n[TEST] Saving chatbot message...")
    chat_id = save_chat_message(
        DB_PATH, "Is the mall full?",
        "Elante Mall Ground Floor is at 50% utilization with 50 spots available.",
        "CHECK_AVAILABILITY", user["user_id"]
    )
    print(f"     - Chat ID: {chat_id}")

    # Test fee calculation
    print("\n[TEST] Calculating parking fee (3 hours at mall)...")
    fee = calculate_parking_fee(DB_PATH, "LOC_MALL", 3.0)
    print(f"     - Amount: {fee['amount']} {fee['currency']}")
    print(f"     - Breakdown: {fee['breakdown']}")

    conn.close()
    print("\n" + "=" * 60)
    print("  [OK] ALL 14 TABLES VERIFIED SUCCESSFULLY")
    print("=" * 60)
